### ISSUE TITLE
examples fail

### ISSUE THREAD

**Issue by brendonmoss** [rezzza/Formulate#11]
When including this in my solution with composer the setSubFormula does not work and even when testing with the examples on the doco page they too error indicating they cannot find the parameter that would be the setSubFormula result.

```
        $formula = new Formula('{{ subformula1 }} + {{ variable2 }}');
        $formula->setSubFormula('subformula1', new Formula('subformula1', '({{ variable1 }} - {{ variable2 }} / 100)'));
        $formula->setParameter('variable1', 10);
        $formula->setParameter('variable2', 13);
```
Remember that the above is from the examples on the doco, so its possible I am using this wrong but so would be the examples.

results in an error
```
{
  "error": {
    "type": "Hoa\\Math\\Exception\\UnknownVariable",
    "message": "Variable subformula1 does not exist.",
    "file": "/home/vagrant/platform/vendor/hoa/math/Context.php",
    "line": 220
  }
}
```

is it possible that some changes in hoa have affected expectations on this projects code?

**Comment by stephpy** [comment]
Hi,

This is due to an error in README.md :scream_cat: 
Look at this PR https://github.com/rezzza/Formulate/pull/12

You should pass to [formula object](https://github.com/rezzza/Formulate/blob/master/src/Rezzza/Formulate/Formula.php#L34) directly the arithmetic operation in first argument.

@shouze @tyx is it possible to merge my [PR](https://github.com/rezzza/Formulate/pull/12) please ?

**Comment by shouze** [comment]
@Spy-Seth merged & you're now a `repo collab` ;)

**Comment by stephpy** [comment]
@shouze Welcome @Spy-Seth :D

**Comment by shouze** [comment]
@stephpy Oops, in fact @stephpy is a `repo collab`
